apiVersion: v1
kind: ReplicationController
metadata:
  name: polyglot
spec:
  replicas: 3
  selector:
    app: polyglot
  template:
    metadata:
      name: polyglot
      labels:
        app: polyglot
    spec:
      containers:
        - name: polyglot
          image: ghcr.io/jpwhite3/polyglot-code-server:latest
          ports:
            - containerPort: 9000